# VoxTrace-DFIR runner (PowerShell) - FINAL (stable paths + optional translation)
# Güvenlik/Gizlilik: Path maskeleme, metadata temizliği, transcription maskeleme, temp cleanup

param(
  [switch]$MaskSensitive,  # Transcription'da telefon/e-posta gibi hassas verileri *** ile maskele
  [switch]$NoCleanup       # Temp dosyalarını temizleme (varsayılan: temizlenir)
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Continue"

# --- Script root (single source of truth)
$root = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $root

# --- PowerShell native-command stderr davranışını kapat (PS 7+)
if (Get-Variable -Name PSNativeCommandUseErrorActionPreference -Scope Global -ErrorAction SilentlyContinue) {
  $global:PSNativeCommandUseErrorActionPreference = $false
}

# --- Paths
$inDir   = Join-Path $root "Inputs"
$outDir  = Join-Path $root "Outputs"
$logDir  = Join-Path $root "Logs"
$doneDir = Join-Path $inDir "Done"
New-Item -ItemType Directory -Force -Path $inDir, $outDir, $logDir, $doneDir | Out-Null

# --- Run log
$ts  = Get-Date -Format "yyyyMMdd_HHmmss"
$log = Join-Path $logDir "run_$ts.log"

# --- Dosya yolu maskeleme: C:\Users\KullaniciAdi -> C:\Users\[USER]\...
function Mask-Path([string]$text) {
  if ([string]::IsNullOrEmpty($text)) { return $text }
  return $text -replace '(?i)([A-Z]:\\Users\\)[^\\/]+', '${1}[USER]'
}

function Log([string]$msg) {
  $masked = Mask-Path $msg
  $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $masked
  Add-Content -Path $log -Value $line -Encoding utf8
  Write-Host $line
}

function Ensure-Command([string]$name) {
  if (-not (Get-Command $name -ErrorAction SilentlyContinue)) {
    Log "ERROR: '$name' not found in PATH. Fix PATH or provide full path."
    exit 1
  }
}

# --- Metadata temizliği: TXT/SRT/VTT dosyalarının başı/sonundaki sistem bilgisini kaldır
function Remove-TranscriptMetadata([string]$filePath) {
  if (-not (Test-Path $filePath)) { return }
  try {
    $lines = Get-Content -Path $filePath -Encoding utf8
    if (-not $lines) { return }
    $metaPatterns = @(
      '^[A-Za-z]:\\Users\\',        # Windows user path
      '^/home/[^/]+/',              # Linux home path
      '^Generated by', '^Created by', '^Created on', '^Generated on',
      '^Computer:\s', '^Hostname:\s', '^User:\s', '^Machine:\s',
      '^\[.*\](path|file)='
    )
    $trimStart = 0
    $trimEnd = $lines.Count
    foreach ($i in 0..([Math]::Min(4, $lines.Count - 1))) {
      $line = $lines[$i].Trim()
      if ([string]::IsNullOrEmpty($line)) { $trimStart = $i + 1; continue }
      $isMeta = $false
      foreach ($p in $metaPatterns) { if ($line -match $p) { $isMeta = $true; break } }
      if ($isMeta) { $trimStart = $i + 1 } else { break }
    }
    for ($i = $lines.Count - 1; $i -gt [Math]::Max($trimStart, $lines.Count - 6); $i--) {
      $line = $lines[$i].Trim()
      if ([string]::IsNullOrEmpty($line)) { $trimEnd = $i; continue }
      $isMeta = $false
      foreach ($p in $metaPatterns) { if ($line -match $p) { $isMeta = $true; break } }
      if ($isMeta) { $trimEnd = $i } else { break }
    }
    if ($trimStart -gt 0 -or $trimEnd -lt $lines.Count) {
      $endIdx = [Math]::Max($trimStart, $trimEnd - 1)
      $filtered = $lines[$trimStart..$endIdx]
      if ($filtered) {
        $filtered -join "`n" | Set-Content -Path $filePath -Encoding utf8 -NoNewline
      }
    }
  } catch {
    Log "[WARN] Metadata temizlenemedi: $filePath - $_"
  }
}

# --- Transcription maskeleme: telefon ve e-posta adreslerini *** ile maskele
function Invoke-TranscriptionMask([string]$filePath) {
  if (-not (Test-Path $filePath)) { return }
  try {
    $content = Get-Content -Path $filePath -Raw -Encoding utf8
    if ([string]::IsNullOrWhiteSpace($content)) { return }
    $content = $content -replace '\b[\d]{3}[-.\s]?[\d]{3}[-.\s]?[\d]{2}[-.\s]?[\d]{2}\b', '***'
    $content = $content -replace '\b[\d]{4}[-.\s]?[\d]{3}[-.\s]?[\d]{2}[-.\s]?[\d]{2}\b', '***'
    $content = $content -replace '\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b', '***'
    $content | Set-Content -Path $filePath -Encoding utf8 -NoNewline
  } catch {
    Log "[WARN] Transcription maskeleme basarisiz: $filePath - $_"
  }
}

# --- Temp dosyalarini temizle (hassas veri sizintisini onle)
function Invoke-CleanupTemp {
  $cleaned = 0
  $tempPaths = @(
    (Join-Path $root "temp_audio")
  )
  foreach ($d in $tempPaths) {
    if (Test-Path $d) {
      try {
        Remove-Item $d -Recurse -Force -ErrorAction Stop
        $cleaned++
        Log "[CLEANUP] Temizlendi: $d"
      } catch {
        Log "[WARN] Cleanup atlandi: $d - $_"
      }
    }
  }
  if ($env:TEMP) {
    Get-ChildItem $env:TEMP -Filter "voxtrace_*" -Directory -ErrorAction SilentlyContinue | ForEach-Object {
      try {
        Remove-Item $_.FullName -Recurse -Force -ErrorAction Stop
        $cleaned++
        Log "[CLEANUP] Temizlendi: $($_.FullName)"
      } catch { }
    }
  }
  if ($cleaned -gt 0) { Log "[CLEANUP] Toplam $cleaned temp oge temizlendi." }
}

Log "Start"
Log "ROOT=$root"
Log "IN=$inDir"
Log "OUT=$outDir"
Log "LOG=$log"

# --- Required commands
Ensure-Command "ffmpeg"
Ensure-Command "whisper"
Ensure-Command "python"

# --- Language settings
# NOTE: translate_txt.py / translate_srt.py supports src/tgt; set src='auto' if you want autodetect.
$srcLang     = "auto"
$tgtLang     = "tr"

# Whisper language:
# - If you pass --language, Whisper may force that language.
# - Using "English" is OK for EN-only audio; for mixed audio consider removing --language.
$whisperLang = "English"

# --- Collect input files
$files = Get-ChildItem $inDir -File | Where-Object {
  $_.Name -match '\.(wav|mp3|m4a|mp4|mkv|mov|webm)$'
}

if (-not $files) {
  Log "No input files found."
  exit 0
}

foreach ($f in $files) {
  Log "=============================="
  Log "File=$($f.Name)"

  $base    = [IO.Path]::GetFileNameWithoutExtension($f.Name)
  $thisOut = Join-Path $outDir $base
  New-Item -ItemType Directory -Force -Path $thisOut | Out-Null

  $mp3 = Join-Path $thisOut "$base.mp3"
  $txt = Join-Path $thisOut "$base.txt"
  $srt = Join-Path $thisOut "$base.srt"

  # --------------------------
  Log "[1/4] Audio prep"
  if ($f.Extension -ieq ".mp3") {
    Copy-Item -Force $f.FullName $mp3
    Log "Audio already mp3 -> copied"
  } else {
    # ffmpeg stderr'e progress basar; bunu hata gibi görme
    $PSNativeCommandUseErrorActionPreference = $false
    $ErrorActionPreference = "Continue"

    & ffmpeg -y -i $f.FullName -vn -acodec mp3 -ab 128k $mp3 2>&1 |
      ForEach-Object { Mask-Path $_ } |
      Out-File -FilePath $log -Append -Encoding utf8

    if ($LASTEXITCODE -ne 0) {
      Log "ERROR: ffmpeg failed with exit code $LASTEXITCODE"
      continue
    }
    Log "ffmpeg OK -> $mp3"
  }

  # --------------------------
  Log "[2/4] Whisper transcribe (CUDA)"
  & whisper $mp3 --model medium --device cuda --task transcribe --language $whisperLang --output_format all --output_dir $thisOut 2>&1 |
    ForEach-Object { Mask-Path $_ } |
    Out-File -FilePath $log -Append -Encoding utf8

  if ($LASTEXITCODE -ne 0) {
    Log "ERROR: whisper failed with exit code $LASTEXITCODE"
    continue
  }
  Log "whisper OK -> outputs in $thisOut"

  # --------------------------
  # Metadata temizliği (TXT, SRT, VTT)
  foreach ($ext in @("txt", "srt", "vtt")) {
    $f = Join-Path $thisOut "$base.$ext"
    if (Test-Path $f) { Remove-TranscriptMetadata $f }
  }

  # --------------------------
  # Transcription maskeleme (opsiyonel: -MaskSensitive ile)
  if ($MaskSensitive) {
    foreach ($ext in @("txt", "srt", "vtt", "tsv")) {
      Get-ChildItem $thisOut -Filter "*.$ext" -ErrorAction SilentlyContinue | ForEach-Object {
        Invoke-TranscriptionMask $_.FullName
      }
    }
    Log "[INFO] Hassas veri maskeleme uygulandi"
  }

  # --------------------------
  # [3/4] TXT translate (optional, non-blocking)
  Log "[3/4] TXT translate"
  $translateTxtPy  = Join-Path $root "translate_txt.py"
  $translateTxtLog = Join-Path $logDir ("translate_txt_{0}_{1}.log" -f $base, $ts)

  Log ("[DEBUG] translateTxtPy={0} exists={1}" -f $translateTxtPy, (Test-Path $translateTxtPy))
  Log ("[DEBUG] txt={0} exists={1}" -f $txt, (Test-Path $txt))

  if ((Test-Path $translateTxtPy) -and (Test-Path $txt)) {
    & python $translateTxtPy $txt $srcLang $tgtLang $thisOut $translateTxtLog

    if ($LASTEXITCODE -ne 0) {
      Log "[WARN] translate_txt.py failed (exit=$LASTEXITCODE). See: $translateTxtLog"
    } else {
      Log "[INFO] TXT translate OK"
    }
  } else {
    Log "[WARN] TXT translate skipped (missing script or txt file)."
  }

  # --------------------------
  # [4/4] SRT translate (optional, non-blocking)
  Log "[4/4] SRT translate"
  $translateSrtPy  = Join-Path $root "translate_srt.py"
  $translateSrtLog = Join-Path $logDir ("translate_srt_{0}_{1}.log" -f $base, $ts)

  Log ("[DEBUG] translateSrtPy={0} exists={1}" -f $translateSrtPy, (Test-Path $translateSrtPy))
  Log ("[DEBUG] srt={0} exists={1}" -f $srt, (Test-Path $srt))

  if ((Test-Path $translateSrtPy) -and (Test-Path $srt)) {
    & python $translateSrtPy $srt $srcLang $tgtLang $thisOut $translateSrtLog

    if ($LASTEXITCODE -ne 0) {
      Log "[WARN] translate_srt.py failed (exit=$LASTEXITCODE). See: $translateSrtLog"
    } else {
      Log ("[INFO] SRT translate OK -> {0}" -f (Join-Path $thisOut ($base + ".tr.srt")))
    }
  } else {
    Log "[WARN] SRT translate skipped (missing script or srt file)."
  }

  # Metadata temizliği: ceviri ciktilarinda da
  foreach ($trFile in @("$base.$tgtLang.txt", "$base.$tgtLang.srt")) {
    $fp = Join-Path $thisOut $trFile
    if (Test-Path $fp) { Remove-TranscriptMetadata $fp }
  }

  # --------------------------
  # Successful processing -> move to Done
  Move-Item -Force $f.FullName $doneDir
  Log "OK Done -> $thisOut"

  # --------------------------
  # Optional: Threat Intel lookup via VirusTotal
  # Enable by setting env var: VOXTRACE_THREAT_INTEL=1 and providing VT_API_KEY
  $tiJson = $null
  if ($env:VOXTRACE_THREAT_INTEL -eq "1") {
    $ti = Join-Path $root "threat_intel.py"
    if (Test-Path $ti) {
      if (-not $env:VT_API_KEY) {
        Log "[WARN] Threat Intel enabled but VT_API_KEY is not set; skipping."
      } else {
        Log "[TI] VirusTotal lookup (Outputs=$thisOut)"
        $tiJson = Join-Path $logDir ("threat_intel_{0}_{1}.json" -f $base, $ts)
        & python $ti $thisOut --out $tiJson 2>&1 |
          ForEach-Object { Mask-Path $_ } |
          Out-File -FilePath $log -Append -Encoding utf8
      }
    } else {
      Log "[WARN] threat_intel.py not found; skipping."
    }
  }

  # --------------------------
  # Optional: PDF report generation
  # Enable by setting env var: VOXTRACE_REPORT=1
  if ($env:VOXTRACE_REPORT -eq "1") {
    $rep = Join-Path $root "reporting_engine.py"
    if (Test-Path $rep) {
      $pdf = Join-Path $logDir ("report_{0}_{1}.pdf" -f $base, $ts)
      Log "[REPORT] Generating PDF -> $pdf"
      $args = @($rep, $thisOut, "--case", $base, "--run-log", $log, "--out", $pdf)
      if ($tiJson -and (Test-Path $tiJson)) {
        $args += @("--threat-intel-json", $tiJson)
      }
      & python @args 2>&1 | ForEach-Object { Mask-Path $_ } | Out-File -FilePath $log -Append -Encoding utf8
    } else {
      Log "[WARN] reporting_engine.py not found; skipping report."
    }
  }
}

# --------------------------
# Temp dosyalarini temizle (NoCleanup ile atlanabilir)
if (-not $NoCleanup) {
  Invoke-CleanupTemp
}

Log "Finished"